### ISSUE TITLE
Changing from Chrome to Firefox

### ISSUE THREAD

**Issue by theSkele** [ChristianPerez34/AutoCryptoClaimer#1]
In crypto_claimer.py simply replace

"import time

from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

class CryptoClaimer:
    def __init__(self):
        self.crypto_faucets = {}
        self.driver = None

    def start_collecting_crypto(self):
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("window-size=1920,1080")
        chrome_options.add_argument("--log-level=3")

        self.driver = webdriver.Chrome(chrome_options=chrome_options, service_log_path="NUL")
        self.driver.maximize_window()"
with
"import time

from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

class CryptoClaimer:
    def __init__(self):
        self.crypto_faucets = {}
        self.driver = None

    def start_collecting_crypto(self):
        firefox_options = Options()
        firefox_options.add_argument("--headless")
        firefox_options.add_argument("window-size=1920,1080")
        firefox_options.add_argument("--log-level=3")

        self.driver = webdriver.Firefox(firefox_options=firefox_options, service_log_path="NUL")
        self.driver.maximize_window()"

Now firefox support instead of chrome, because its better.
I cannot figure out Githubs formatting, sorry for the ugliness

**Comment by ChristianPerez34** [comment]
Hi,

I added some changes that you might benefit from. You are now able to choose which driver you wish to use when running the bot. By default it will run on Chrome. Tell me what you think and if this works for you. Any suggestions and contributions are welcome!

https://github.com/ChristianPerez34/AutoCryptoClaimer/pull/3

**Comment by theSkele** [comment]
I love it, idk what to suggest as its simply choosing a driver. Thank you sorry for late reply
