### ISSUE TITLE
Unsupported file type .txt

### ISSUE THREAD

**Issue by byte05** [ChristianPerez34/AutoCryptoClaimer#10]
I use txt file.
`File "app.py", line 36
    f"Unsupported file type: {crypto_faucets_file.suffix}\nSupported file type: .txt"`

**Comment by ChristianPerez34** [comment]
Verify that the ext is in fact `txt`

If possible, please share parameters used when running the script

**Comment by byte05** [comment]
parameters: python app.py logins.txt

Python 2.7.16. All requirements are installed.

**Comment by ChristianPerez34** [comment]
> parameters: python app.py logins.txt
> 
> Python 2.7.16. All requirements are installed.

I am unable to reproduce this issue. Make sure you are running the latest version of the repo and that the path is correct.

**Comment by ChristianPerez34** [comment]
I recommend using python3.6+ I’m using features that are not present in python 2.7

**Comment by byte05** [comment]
Thanks. It works on Python 3.6.8.
