### ISSUE TITLE
Sorry to bother again sir

### ISSUE THREAD

**Issue by findasolution** [ChristianPerez34/AutoCryptoClaimer#20]
Is this supposed to happen when I run app.py? C:\Users\A-10\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\util.py:94: PytzUsageWarning: The zone attrcific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprereadthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
C:\Users\A-10\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\triggers\interval.py:66: PytzUsageWarning: e method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)

DevTools listening on ws://127.0.0.1:58609/devtools/browser/6ef8b675-f827-4bc4-9611-8a01d74efaad
Collecting crypto faucets...
Visiting https://freebinancecoin.com/free
Logging in...
Claiming crypto...
Already claimed...
Current balance:

And then I go and check my account and I am on 0

**Comment by ChristianPerez34** [comment]
Have not run this app for a while. Although I'm sure it's probably not supposed to happen. Could be that website UI changed or something different altogether

**Comment by findasolution** [comment]
Ok, thanks
