### ISSUE TITLE
The Bot Doesn't Enter Email and Password

### ISSUE THREAD

**Issue by ghost** [ChristianPerez34/AutoCryptoClaimer#5]
tried switching browser to firefox but it didn't work out well
using python 3.8.0 btw

**Comment by ChristianPerez34** [comment]
Are you getting any errors? Will look into this

**Comment by ghost** [comment]
No, it doesn't give me any errors.
```Collecting crypto faucets...
Visiting https://freenem.com/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://freecardano.com/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://coinfaucet.io/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://freebitcoin.io/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://freetether.com/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://freeusdcoin.com/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://freeethereum.com/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://free-tron.com/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

Visiting https://freebinancecoin.com/
Logging in...
Claiming crypto...
Already claimed...
Current balance:

```

**Comment by ChristianPerez34** [comment]
> No, it doesn't give me any errors.
> 
> ```
> Visiting https://freenem.com/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://freecardano.com/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://coinfaucet.io/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://freebitcoin.io/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://freetether.com/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://freeusdcoin.com/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://freeethereum.com/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://free-tron.com/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> 
> Visiting https://freebinancecoin.com/
> Logging in...
> Claiming crypto...
> Already claimed...
> Current balance:
> ```

I've experienced a similar issue with the latest firefox and geckodriver. Still looking into this, may try out other browsers as well other than chrome to see if the issue repeats itself

**Comment by ChristianPerez34** [comment]
Did  a few fixes and I got firefox working! I only tested for one of the supported sites though.
